---
- name: Managing Software Packages
  hosts: Centnode
  vars:
          my_package: virt-manager
  tasks:
          - name: Install package
            yum:
                    name: "{{ my_package }}"
                    state: present
          - name: Update package facts
            package_facts:
                    manager: auto
          - name: Show package facts for {{ my_package }}
            debug:
                    var: ansible_facts.packages[my_package]
            when: my_package in ansible_facts.packages
