---
- name: Preparing localhost
  hosts: localhost
  tasks:
          - name: Create the local user, including SSH key
            user:
                    name: "{{ username }}"
                    generate_ssh_key: true
                    ssh_key_comment: "{{ username }}@{{ ansible_fqdn }}"
          - name: create a directory to store the file
            file:
                    name: "{{ username }}"
                    state: directory
          - name: Copy the local user ssh key to temporary {{username }} key
            shell: 'cat /home/{{ username }}/.ssh/id_rsa.pub > {{ username }}/id_rsa.pub'
          - name: Verify that the file exists
            command: ls -l {{ username }}/
- name: Setting up remote host
  hosts: Centnode
  tasks:
          - name: create remote user, no need for SSH key 
            user:
                    name: "{{ username }}"
          - name: use authorized_key to set the password 
            authorized_key:
                    user: "{{ username }}"
                    key: "{{ lookup('file', './'+ username + '/id_rsa.pub')}}"
                                      
