---
- name: run a cron job
  hosts: all
  tasks:
          - name: run a periodic job
            cron:
                    name: "run logger"
                    minute: "0"
                    hour: "5"
                    job: "logger IT IS 5 AM"
