---
- name: get vg sizes
  ignore_errors: yes
  hosts: Centnode
  tasks:
          - name: set vgroup sizes in variables
            set_fact:
                    vgsize: "{{ansible_facts['lvm']['vgs']['cl']['size_g'] | int}}"
          - name: debug this {{vgsize}}
            debug:
                    msg: The value of vgsize is {{vgsize}}

          - name: testing big vgsize value
            debug:
                    msg: The value of vgsize is bigger than 5 
            when: vgsize | int > 5 
          - name: testing small vgsize value
            debug:
                    msg: The value of vgsize is smaller than 5 
            when: vgsize | int < 5 
