---
- name: Managing the boot process and services
  hosts: all
  tasks:
          - name: adding a line to file before rebooting
            lineinfile:
                    create: true
                    state: present
                    path: /tmp/rebooted
                    insertafter: EOF
                    line: rebooted at {{ ansible_facts['date_time']['time']}}:{{ ansible_facts['date_time']['second']}}
          - name: Run a job on reboot
            cron:
                    name: "run on reboot"
                    state: present
                    special_time: reboot
                    job: "echo rebooted at $(date) >> /tmp/rebooted"
          - name: reboot managed hosts
            reboot:
                    msg: rebbot initiated by Ansible
                    test_command: whoami
          - name: show reboot success
            debug:
                    msg: Just rebooted successfully 

