---
- name: Install FTP server
  yum:
          name: vsftpd
          state: latest
- name: Allow anonymous access to FTP
  lineinfile:
          path: /etc/vsftpd/vsftpd.conf
          regexp: '^anonymous_enable=NO'
          line: anonymous_enable=Yes
- name: Start FTP server
  service:
          name: vsftpd
          state: started
          enabled: yes
- name: Open firewall for FTP
  firewalld:
          service: ftp
          state: enabled
          immediate: yes
          permanent: yes
